name: Build Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CANDIDATE_VERSION: 0.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.16
      uses: actions/setup-node@v1
      with:
        node-version: 12.16

    - name: Read app version from package.json
      uses: culshaw/read-package-node-version-actions@v1
      id: app-node-version

    - name: Set Version
      run: echo ::set-env name=CANDIDATE_VERSION::${{ steps.app-node-version.outputs.version }}

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Build DEV
      if: github.ref != 'refs/heads/master'
      run: npm run build-dev

    - name: Build PRD
      if: github.ref == 'refs/heads/master'
      run: npm run build-prd

    - name: Archive artifact
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: candidates-${CANDIDATE_VERSION}
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: candidates-${CANDIDATE_VERSION}
