name: Build Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: invalid
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.16
      uses: actions/setup-node@v1
      with:
        node-version: 12.16

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Build DEV
      if: github.ref != 'refs/heads/master'
      run: npm run build-dev

    - name: Build PRD
      if: github.ref == 'refs/heads/master'
      run: npm run build-prd

    - name: Build image
      run: docker build . --file Dockerfile

    - name: Login to Heroku Container
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Push Heroku DEV
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      if: github.ref != 'refs/heads/master'
      run: |
        heroku container:push -a candidates-app-dev web
        heroku container:release -a candidates-app-dev web

    - name: Push Heroku PRD
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      if: github.ref == 'refs/heads/master'
      run: |
        heroku container:push -a candidates-app-prd web
        heroku container:release -a candidates-app-prd web
