name: Build Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.16
      uses: actions/setup-node@v1
      with:
        node-version: 12.16

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Build DEV
      if: github.ref != 'refs/heads/master'
      run: npm run build-dev
      # run: |
      #   npm run build-dev
      #   docker build . --file Dockerfile

    - name: Build PRD
      if: github.ref == 'refs/heads/master'
      run: npm run build-prd

    - name: Build image
      run: docker build . --file Dockerfile

    # - name: Archive artifact
    #   if: success()
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: dist
    #     path: dist
    # - name: Archive NGINX
    #   if: success()
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: NGINX
    #     path: NGINX

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v1
  #   - name: Download build
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: dist
  #       path: ~/app
  #   - name: Download NGINX
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: NGINX
  #       path: ~/nginx
  #   - name: Build image
  #     run: docker build . --file Dockerfile
  #     # run: docker build . --file Dockerfile --tag $IMAGE_NAME

